#!/bin/bash

batt() {
pwr=$(cat /sys/class/power_supply/BAT0/capacity)
sts=$(cat /sys/class/power_supply/BAT0/status)
case "$sts" in
	"Charging") echo -e "+$pwr%";;
	"Discharging") echo -e "$pwr%" ;;  *) echo -e "?$pwr%" ;;
esac; }

volume() {
	vol="$(awk -F"[][]" '/Left:/ { print $2 }' <(amixer sget Master))"
	echo -e "$vol"; }

backlight() {
	bgt="$(brightnessctl | grep -oP '\d+(?=%)')"
	echo -e "$bgt%"; }

clock() {
	dte="$(date +"%A   󱨰  %d/%b   󰔛  %H-%M"| sed 's/  / /g')"
	echo -e "$dte"; }

network(){
	ssid="$(iw dev | grep ssid | awk '{print $2}')"
	echo -e "$ssid"; }

keyboard(){
	kb=$(setxkbmap -query | awk '/layout/ {print $2}')
	echo -e "$kb"; }

updates(){ 
	upd=$(checkupdates | wc -l) 
	echo -e "$upd"; }

# /---/	main loop
while true; do
	xsetroot -name "  󰘎 :$(keyboard)  󰕾 $(volume)  󰌶 $(backlight)  󰂀 $(batt)  󰤥  $(network) - $(clock)   "
	sleep 5s
done &

