#!/bin/bash

## BATT
power() {
PWR=$(cat /sys/class/power_supply/BAT0/capacity)
echo -e "$PWR%"
}

## VOL
volume() {
VOL="$(awk -F"[][]" '/Left:/ { print $2 }' <(amixer sget Master))"
echo -e "$VOL"
}

## SCREEN BRIGHTNESS
backlight() {
#BLT="$(xbacklight -get | awk '{print int($1)}')"
BLT="$(brightnessctl | grep -oP '\d+(?=%)')"
echo -e "$BLT%"	
}

## DATE
clock() {
dte="$(date +"%A   󱨰  %d/%b   󰦖  %H-%M"| sed 's/  / /g')"
echo -e "$dte "
}

while true; do
	xsetroot -name "   󰕾  $(volume)  󰌶  $(backlight)  󰂀  $(power)  -  $(clock)   "
	sleep 5s
done &

